// src/common/response/api-error-codes.ts

export enum ApiErrorCode {
  INVALID_EMAIL = 'INVALID_EMAIL',

  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED = 'OTP_ATTEMPTS_EXCEEDED',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DUPLICATE_USER = 'DUPLICATE_USER',
  INVALID_REGISTRATION_KEY = 'INVALID_REGISTRATION_KEY',
}
